name: MicaForEveryone

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-2019  # Matches the original workflow's environment
    env:
      SOLUTION_FILE_PATH: MicaForEveryone.sln
      CONFIGURATION: Release
      PLATFORM: x64
      OUTPUT_DIR: bin\x64\Release
      EXE_NAME: MicaForEveryone-x64-Release.exe

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Install Dependencies (v142 Toolset & SDK)
      shell: pwsh
      run: |
        choco install visualstudio2019buildtools --package-parameters `
          "--add Microsoft.VisualStudio.Component.VC.v142.x86.x64 `
          --add Microsoft.VisualStudio.Component.Windows10SDK `
          --add Microsoft.VisualStudio.Component.VC.ATL" -y --no-progress

    - name: Verify ATL Headers
      shell: pwsh
      run: |
        $atlPath = "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\include\atlstr.h"
        if (-Not (Test-Path $atlPath)) {
          Write-Error "ATL headers not found at $atlPath"
          exit 1
        }
        Write-Output "ATL headers found at $atlPath"

    - name: Build Solution
      run: |
        msbuild ${{ env.SOLUTION_FILE_PATH }} /m ^
          /p:Configuration=${{ env.CONFIGURATION }} ^
          /p:Platform=${{ env.PLATFORM }} ^
          /p:PlatformToolset=v142 ^
          /p:OutputPath=${{ env.OUTPUT_DIR }}

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ env.EXE_NAME }}
        path: ${{ env.OUTPUT_DIR }}\MicaForEveryone.exe



