name: Build MicaForEveryone

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      working-directory: ${{ github.workspace }}\src  # Use backslashes for Windows paths
      run: msbuild /t:Restore "MicaForEveryone.sln"

    - name: Build solution (x64)
      working-directory: ${{ github.workspace }}\src  # Use backslashes for Windows paths
      run: |
        msbuild /m `
                /p:Configuration=${{ matrix.configuration }} `
                /p:Platform="x64" `
                /p:OutputPath="bin\x64\${{ matrix.configuration }}" `
                "MicaForEveryone.sln"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MicaForEveryone-x64-${{ matrix.configuration }}
        path: src/bin/x64/${{ matrix.configuration }}/MicaForEveryone.exe
