name: Build MicaForEveryone

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        configuration: [Release]
    runs-on: windows-latest
    env:
      SOLUTION_FILE_PATH: src/MicaForEveryone.sln  # Correct path to the solution file
      VERSION: 2.0.2  # Update this with your actual version

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: msbuild /t:Restore "${{ env.SOLUTION_FILE_PATH }}"

    - name: Build solution (x64)
      run: |
        msbuild /m `
                /p:Configuration=${{ matrix.configuration }} `
                /p:Platform="x64" `
                /p:OutputPath="bin\x64\${{ matrix.configuration }}" `
                "${{ env.SOLUTION_FILE_PATH }}"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: MicaForEveryone-${{ env.VERSION }}-x64-${{ matrix.configuration }}
        path: src/bin/x64/${{ matrix.configuration }}/MicaForEveryone.exe
